name: Version

on:
  workflow_dispatch:
    inputs: 
      type:
        description: 'Version type'     
        required: true
        default: 'patch'
      name:
        description: 'name'     
        required: true
        default: 'BilelJegham'      
      email:
        description: 'Version type'     
        required: true
        default: '@gmail.com'

jobs:
  push-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          git config --global user.email "${{ github.event.inputs.email }}"
          git config --global user.name "${{ github.event.inputs.name }}"
          npm version ${{ github.event.inputs.type }}
          git push --follow-tags
      
