name: Version

on:
  workflow_dispatch:
    inputs: 
      type:
        description: 'Version type'     
        required: true
        default: 'minor'
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          npm version ${{ github.event.inputs.type }}
          git push --follow-tags
      
